name: Build and Deploy Flutter Web to Firebase

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.flutter
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Clean Build Cache
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Set up Channel ID
        id: generate_channel_id
        run: |
          DATE=$(date +'%Y%m%d')
          FILE=".channel_id_log"
            
          # Check and update count
          if [ -f "$FILE" ]; then
            LAST_DATE=$(cut -c1-8 "$FILE")
            if [ "$LAST_DATE" == "$DATE" ]; then
              LAST_COUNT=$(cut -c9- "$FILE")
              COUNT=$(printf "%02d" $((10#$LAST_COUNT + 1)))
            else
              COUNT="01"
            fi
          else
            COUNT="01"
          fi
            
          echo "${DATE}${COUNT}" > $FILE
          echo "channelId=jay-sathvara-${DATE}${COUNT}" >> $GITHUB_OUTPUT

      - name: Use channelId
        run: |
          echo "Generated Channel ID: ${{ steps.generate_channel_id.outputs.channelId }}"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CICD_DEMO_73E7B }}
          projectId: cicd-demo-73e7b
          channelId: ${{ steps.generate_channel_id.outputs.channelId }}
          expires: 30d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
